[package]
name = "piecemeal-build"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
piecemeal = { path = "../piecemeal" }
nom = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
walkdir = { version = "2", default-features = false }
tempfile = "3"

[[test]]
name = "cargo_output_dir_with_out_dir_set"
harness = false

[[test]]
name = "cargo_output_dir_without_out_dir_set"
harness = false

[[test]]
name = "cargo_output_dir_with_absolute_path"
harness = false

[[test]]
name = "cargo_output_dir_overwrites"
harness = false
