[workspace]
members = [
  "piecemeal",
  "piecemeal-build",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/tobz/piecemeal"

[workspace.dependencies]
byteorder = { version = "1.5", default-features = false }
nom = { version = "7", default-features = false, features = ["std"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
