syntax = "proto3";

package metrics_example;

message Metadata {
	uint32 origin_product_id = 1;
    uint32 origin_service_id = 2;
}

message MetricPayload {
    enum AggregationType {
      UNSPECIFIED = 0;
      DELTA = 1;
      CUMULATIVE = 2;
    }

    message MetricPoint {
        double value = 1;
        int64 unix_timestamp = 2;
    }

    message MetricSeries {
        string name = 1;
        repeated string tags = 2;
        repeated MetricPoint points = 3;
        AggregationType aggregation_type = 4;
        Metadata metadata = 5;
    }

    repeated MetricSeries series = 1;
}
